import type {
  CanvasAspectRatio,
  CanvasBackgroundMode,
  PipPosition,
  RotationMode,
} from "../../services/videoMixService";
import type {
  NarratedSubtitlePosition,
  NarratedSubtitleSize,
  TtsSynthesisResult,
} from "../../features/tts";
import type { AsrRecognitionResult } from "../../features/asr";
import type { ToolKey } from "../../types/workbench";
import type { SceneSensitivity, SplitMode } from "../../features/materials";
import type { WatermarkRemovalSettings, WatermarkSettings } from "../../features/watermark";
import type {
  EncoderCapabilities,
  OutputFrameRate,
  OutputQuality,
  OutputResolution,
  VideoEncoder,
} from "../../types/outputSettings";
import type { EntranceEffect, FrameOperationSettings, FusionSettings, PlaybackSpeedMode, VideoVisualStyle } from "../../services/videoMixService";

export interface ToolSettingModalProps {
  activeTool: ToolKey | null;
  isSplitting: boolean;
  isMixing: boolean;
  isBatchMixing: boolean;
  isExporting: boolean;
  splitError: string | null;
  splitOutputDirectory: string | null;
  splitSegmentCount: number | null;
  randomPickError: string | null;
  outputDirectory: string | null;
  outputDirectoryError: string | null;
  segmentDurationSeconds: number;
  splitMode: SplitMode;
  sceneSensitivity: SceneSensitivity;
  minimumSegmentSeconds: number;
  maximumSegmentSeconds: number;
  randomPickCount: number;
  batchGenerateCount: number;
  canvasAspectRatio: CanvasAspectRatio;
  canvasBackgroundMode: CanvasBackgroundMode;
  applyHorizontalMirror: boolean;
  applyVerticalMirror: boolean;
  smoothRemixEnabled: boolean;
  playbackSpeed: number;
  rotationMode: RotationMode;
  brightness: number;
  contrast: number;
  saturation: number;
  effectScale: number;
  zoomEnabled: boolean;
  zoomMode: import("../../services/videoMixService").DynamicZoomMode;
  zoomMinScale: number;
  zoomMaxScale: number;
  zoomMinDurationSeconds: number;
  zoomMaxDurationSeconds: number;
  cropBlackBars: boolean;
  randomRotationMinDegrees: number;
  randomRotationMaxDegrees: number;
  sharpness: number;
  noiseReduction: number;
  temperature: number;
  visualStyle: VideoVisualStyle;
  glowEnabled: boolean;
  grainEnabled: boolean;
  vignetteEnabled: boolean;
  playbackSpeedMode: PlaybackSpeedMode;
  playbackSpeedMin: number;
  playbackSpeedMax: number;
  playbackSegmentMinSeconds: number;
  playbackSegmentMaxSeconds: number;
  frameMaterialFilePath: string | null;
  fusionMaterialFilePath: string | null;
  entranceEffect: EntranceEffect;
  frameOperationSettings: FrameOperationSettings;
  fusionSettings: FusionSettings;
  pipEnabled: boolean;
  pipOverlayFilePath: string | null;
  pipMode: "main" | "external";
  pipMainSizeMin: number;
  pipMainSizeMax: number;
  pipBlurMin: number;
  pipBlurMax: number;
  pipOffsetXMin: number;
  pipOffsetXMax: number;
  pipOffsetYMin: number;
  pipOffsetYMax: number;
  pipPosition: PipPosition;
  pipSizeRatio: number;
  pipOpacity: number;
  pipMargin: number;
  bgmEnabled: boolean;
  bgmAudioFilePath: string | null;
  originalVolume: number;
  originalVolumeMin: number;
  originalVolumeMax: number;
  originalFadeEnabled: boolean;
  dynamicAudioAdjustEnabled: boolean;
  bgmVolume: number;
  bgmVolumeMin: number;
  bgmVolumeMax: number;
  bgmFadeEnabled: boolean;
  bgmLoopPlaybackEnabled: boolean;
  bgmFadeInSeconds: number;
  bgmFadeOutSeconds: number;
  selectedCoverUrl: string | null;
  selectedCoverPath: string | null;
  coverFrameSeconds: number;
  isGeneratingCover: boolean;
  coverError: string | null;
  ttsText: string;
  ttsSpeaker: string;
  ttsResourceId: string;
  ttsConfigured: boolean;
  isLoadingTtsConfig: boolean;
  isGeneratingTts: boolean;
  isGeneratingNarratedVideo: boolean;
  ttsConfigError: string | null;
  ttsError: string | null;
  narratedVideoError: string | null;
  narrationProgressText: string | null;
  ttsVideoEnabled: boolean;
  ttsKeepOriginalAudio: boolean;
  ttsOriginalAudioVolume: number;
  ttsSubtitleEnabled: boolean;
  ttsSubtitlePosition: NarratedSubtitlePosition;
  ttsSubtitleSize: NarratedSubtitleSize;
  ttsResult: TtsSynthesisResult | null;
  ttsAudioUrl: string | null;
  asrConfigured: boolean;
  asrResourceId: string;
  asrSourceFilePath: string | null;
  asrSourceFileName: string | null;
  isLoadingAsrConfig: boolean;
  isRecognizingAsr: boolean;
  asrError: string | null;
  asrResult: AsrRecognitionResult | null;
  isSavingAsrToLibrary: boolean;
  asrLibraryFeedback: string | null;
  watermarkSettings: WatermarkSettings;
  watermarkRemovalSettings: WatermarkRemovalSettings;
  watermarkPreviewUrl: string | null;
  outputResolution: OutputResolution;
  outputFrameRate: OutputFrameRate;
  outputQuality: OutputQuality;
  outputEncoder: VideoEncoder;
  encoderCapabilities: EncoderCapabilities | null;
  encoderDetectionError: string | null;
  isDetectingEncoders: boolean;
}

export type ToolSettingModalEmits = {
  apiConfigChanged: [];
  close: [];
  reset: [tool: ToolKey];
  splitSelectedVideo: [];
  pickSegmentsRandomly: [];
  concatRandomSegments: [];
  generateBatchMixes: [];
  selectOutputDirectory: [];
  openOutputDirectory: [];
  exportSelectedVideo: [];
  selectPipOverlayFile: [];
  selectFrameMaterialFile: [];
  selectFusionMaterialFile: [];
  clearFrameMaterialFile: [];
  clearFusionMaterialFile: [];
  selectBgmAudioFile: [];
  selectBgmAudioFolder: [];
  clearBgmAudioFile: [];
  selectCoverImageFile: [];
  selectCoverImageFolder: [];
  generateCoverFrame: [];
  generateTts: [];
  selectAsrSourceFile: [];
  recognizeAsr: [];
  clearAsrSelection: [];
  saveAsrToLibrary: [];
  saveAndUseAsrScript: [];
  selectWatermarkImage: [];
  detectEncoders: [];
  "update:segmentDurationSeconds": [value: number];
  "update:splitMode": [value: SplitMode];
  "update:sceneSensitivity": [value: SceneSensitivity];
  "update:minimumSegmentSeconds": [value: number];
  "update:maximumSegmentSeconds": [value: number];
  "update:randomPickCount": [value: number];
  "update:batchGenerateCount": [value: number];
  "update:canvasAspectRatio": [value: CanvasAspectRatio];
  "update:canvasBackgroundMode": [value: CanvasBackgroundMode];
  "update:applyHorizontalMirror": [value: boolean];
  "update:applyVerticalMirror": [value: boolean];
  "update:smoothRemixEnabled": [value: boolean];
  "update:playbackSpeed": [value: number];
  "update:rotationMode": [value: RotationMode];
  "update:brightness": [value: number];
  "update:contrast": [value: number];
  "update:saturation": [value: number];
  "update:effectScale": [value: number];
  "update:zoomEnabled": [value: boolean];
  "update:zoomMode": [value: import("../../services/videoMixService").DynamicZoomMode];
  "update:zoomMinScale": [value: number];
  "update:zoomMaxScale": [value: number];
  "update:zoomMinDurationSeconds": [value: number];
  "update:zoomMaxDurationSeconds": [value: number];
  "update:cropBlackBars": [value: boolean];
  "update:randomRotationMinDegrees": [value: number];
  "update:randomRotationMaxDegrees": [value: number];
  "update:sharpness": [value: number];
  "update:noiseReduction": [value: number];
  "update:temperature": [value: number];
  "update:visualStyle": [value: VideoVisualStyle];
  "update:glowEnabled": [value: boolean];
  "update:grainEnabled": [value: boolean];
  "update:vignetteEnabled": [value: boolean];
  "update:playbackSpeedMode": [value: PlaybackSpeedMode];
  "update:playbackSpeedMin": [value: number];
  "update:playbackSpeedMax": [value: number];
  "update:playbackSegmentMinSeconds": [value: number];
  "update:playbackSegmentMaxSeconds": [value: number];
  "update:pipEnabled": [value: boolean];
  "update:pipMode": [value: "main" | "external"];
  "update:pipMainSizeMin": [value: number];
  "update:pipMainSizeMax": [value: number];
  "update:pipBlurMin": [value: number];
  "update:pipBlurMax": [value: number];
  "update:pipOffsetXMin": [value: number];
  "update:pipOffsetXMax": [value: number];
  "update:pipOffsetYMin": [value: number];
  "update:pipOffsetYMax": [value: number];
  "update:pipPosition": [value: PipPosition];
  "update:pipSizeRatio": [value: number];
  "update:pipOpacity": [value: number];
  "update:pipMargin": [value: number];
  "update:bgmEnabled": [value: boolean];
  "update:originalVolume": [value: number];
  "update:originalVolumeMin": [value: number];
  "update:originalVolumeMax": [value: number];
  "update:originalFadeEnabled": [value: boolean];
  "update:dynamicAudioAdjustEnabled": [value: boolean];
  "update:bgmVolume": [value: number];
  "update:bgmVolumeMin": [value: number];
  "update:bgmVolumeMax": [value: number];
  "update:bgmFadeEnabled": [value: boolean];
  "update:bgmLoopPlaybackEnabled": [value: boolean];
  "update:bgmFadeInSeconds": [value: number];
  "update:bgmFadeOutSeconds": [value: number];
  "update:coverFrameSeconds": [value: number];
  "update:ttsText": [value: string];
  "update:ttsSpeaker": [value: string];
  "update:ttsVideoEnabled": [value: boolean];
  "update:ttsKeepOriginalAudio": [value: boolean];
  "update:ttsOriginalAudioVolume": [value: number];
  "update:ttsSubtitleEnabled": [value: boolean];
  "update:ttsSubtitlePosition": [value: NarratedSubtitlePosition];
  "update:ttsSubtitleSize": [value: NarratedSubtitleSize];
  "update:watermarkEnabled": [value: boolean];
  "update:watermarkKind": [value: WatermarkSettings["kind"]];
  "update:watermarkText": [value: string];
  "update:watermarkPosition": [value: WatermarkSettings["position"]];
  "update:watermarkOpacity": [value: number];
  "update:watermarkMargin": [value: number];
  "update:watermarkTextFontSize": [value: number];
  "update:watermarkTextColor": [value: string];
  "update:watermarkImageSizeRatio": [value: number];
  "update:watermarkRemovalEnabled": [value: boolean];
  "update:watermarkRemovalMode": [value: WatermarkRemovalSettings["mode"]];
  "update:watermarkRemovalPosition": [value: WatermarkRemovalSettings["position"]];
  "update:watermarkRemovalSize": [value: WatermarkRemovalSettings["size"]];
  "update:watermarkRemovalMargin": [value: number];
  "update:watermarkRemovalStrength": [value: number];
  "update:watermarkRemovalCoverColor": [value: string];
  "update:watermarkRemovalCoverOpacity": [value: number];
  "update:watermarkRemovalTrackingEnabled": [value: boolean];
  "update:watermarkRemovalTrackingRegionWidthRatio": [value: number];
  "update:watermarkRemovalTrackingRegionHeightRatio": [value: number];
  "update:watermarkRemovalTrackingKeyframes": [value: WatermarkRemovalSettings["trackingKeyframes"]];
  "update:outputResolution": [value: OutputResolution];
  "update:outputFrameRate": [value: OutputFrameRate];
  "update:outputQuality": [value: OutputQuality];
  "update:outputEncoder": [value: VideoEncoder];
  "update:entranceEffect": [value: EntranceEffect];
  "update:frameOperationSettings": [value: FrameOperationSettings];
  "update:fusionSettings": [value: FusionSettings];
};
